### ISSUE TITLE
Add a post property for featured image, please

### ISSUE THREAD

**Issue by guillermomf2001** [vaakash/git-it-write#12]
It would be cool if anybody could add a feature image directly from post properties into the Yaml configguration of the post .md file. Something like this: 

```
---

title: Title of this post
menu_order: 1
post_status: draft
post_excerpt: Excerpt of this post.
post_featured_image: /_images/featured_image.jpg  # <-- featured image URL in a new yaml post property
taxonomy:
    category:
        - Javascript
    post_tag:
        - Javascript-config
        - VSCode

---

# Title post

The rest of the content...
```
