### ISSUE TITLE
Custom taxonomy 

### ISSUE THREAD

**Issue by tblobaum** [vaakash/git-it-write#33]
How do i add a custom taxonomy to a post. 

For example, my post has one to many tags, one to many categories, and one publisher. The custom taxonomy publisher is a clone of the category type.

**Comment by vaakash** [comment]
Hi @tblobaum,

You can add custom taxonomy like below.
https://www.aakashweb.com/docs/git-it-write/writing-posts/#setting-post-properties-like-post-title-tags-custom-fields-etc

```
---
title: Title of the post
menu_order: 1
post_status: publish
post_excerpt: This is a post excerpt
featured_image: _images/post-image.jpg
taxonomy:
    category:
        - category-slug-1
        - category-slug-2
    post_tag:
        - tag-1
        - tag-2
custom_fields:
    field1: value 1
    field2: value 2

---

## My post content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a lacinia orci.
Nunc sodales massa enim, nec consectetur orci tempus ac.
```

Thanks,
Aakash

**Comment by tblobaum** [comment]
```
---
title: Title of the post
menu_order: 1
post_status: publish
post_excerpt: This is a post excerpt
featured_image: _images/post-image.jpg
taxonomy:
    category:
        - category-slug-1
        - category-slug-2
    post_tag:
        - tag-1
        - tag-2
    publisher:
        - publisher-1
custom_fields:
    field1: value 1
    field2: value 2

---

## My post content

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a lacinia orci.
Nunc sodales massa enim, nec consectetur orci tempus ac.
```

Is this correct?
